/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : LED_BLUE.h
**     Project     : PREN
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.066, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-03-31, 08:56, # CodeGen: 0
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : LED_BLUE
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            Anode on port side, HIGH is ON               : no
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void LED_BLUE_Init(void);
**         Deinit     - void LED_BLUE_Deinit(void);
**         On         - void LED_BLUE_On(void);
**         Off        - void LED_BLUE_Off(void);
**         Neg        - void LED_BLUE_Neg(void);
**         Get        - uint8_t LED_BLUE_Get(void);
**         Put        - void LED_BLUE_Put(uint8_t val);
**         SetRatio16 - void LED_BLUE_SetRatio16(uint16_t ratio);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013-2015, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file LED_BLUE.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup LED_BLUE_module LED_BLUE module documentation
**  @{
*/         

#ifndef __LED_BLUE_H
#define __LED_BLUE_H

/* MODULE LED_BLUE. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin2.h"

#include "Cpu.h"

#define LED_BLUE_ClrVal()    LEDpin2_ClrVal() /* put the pin on low level */
#define LED_BLUE_SetVal()    LEDpin2_SetVal() /* put the pin on high level */
#define LED_BLUE_SetInput()  LEDpin2_SetInput() /* use the pin as input pin */
#define LED_BLUE_SetOutput() LEDpin2_SetOutput() /* use the pin as output pin */

#define LED_BLUE_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define LED_BLUE_On() LEDpin2_ClrVal()
/*
** ===================================================================
**     Method      :  LED_BLUE_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_BLUE_Off() LEDpin2_SetVal()
/*
** ===================================================================
**     Method      :  LED_BLUE_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_BLUE_Neg() LEDpin2_NegVal()
/*
** ===================================================================
**     Method      :  LED_BLUE_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_BLUE_Get() (!(LEDpin2_GetVal()))
/*
** ===================================================================
**     Method      :  LED_BLUE_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define LED_BLUE_Init() LED_BLUE_Off()
/*
** ===================================================================
**     Method      :  LED_BLUE_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_BLUE_Put(val)  ((val) ? LED_BLUE_On() : LED_BLUE_Off())
/*
** ===================================================================
**     Method      :  LED_BLUE_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void LED_BLUE_Deinit(void);
/*
** ===================================================================
**     Method      :  LED_BLUE_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LED_BLUE_SetRatio16(uint16_t ratio);
/*
** ===================================================================
**     Method      :  LED_BLUE_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END LED_BLUE. */

#endif
/* ifndef __LED_BLUE_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
